add stronger flashlight + change mp7 recoil
BourbonWarfare/POTATO pull request #452
Opened 2023-11-06 23:57 UTC by AChesheireCat

Adds an offshoot of Carl's Flashlights to POTATO - these flashlights inherit from CUP's tactical flashlights and add a flashlight that has three modes - a beam that extends 150m but in a tiny cone, a normal light that extends like 65m in a larger cone, and a floodlight that extends 25m but in a huge cone.

Adjusts the CUP MP7 recoil to be usable - takes notes from the CUP MP5A5 recoil.

2023-11-06 23:59 UTC, TheCandianVendingMachine requested changes

2023-11-06 23:59 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +	class potato_stronger_flashlights
Change to CBA/Potato standard (Everywhere)

2023-11-06 23:59 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +		author="Carl, Chesheire";
Tabs -> Spaces

2023-11-07 00:01 UTC, TheCandianVendingMachine commented
Place for standards: https://ace3.acemod.org/wiki/development/coding-guidelines

2023-11-07 00:40 UTC, TheCandianVendingMachine requested changes
nearly there

2023-11-07 00:40 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/$PBOPREFIX$
> +z\potato\addons\strongerFlashLights
`strongerFlashLights` -> `strongerFlashlights` (this on me sorry)

2023-11-07 00:40 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/CfgWeapons.hpp
> +class cfgWeapons
`cfgWeapons` -> `CfgWeapons`

2023-11-07 00:40 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/CfgWeapons.hpp
> +{
Brace has to be on same line as `CfgWeapons`

2023-11-07 00:40 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/CfgWeapons.hpp
> +    class GVAR(CUP_LED_flashlight_Beam): cup_acc_flashlight
Brace has to be on same line

Same for all subsequent braces, if we have `class BLAH` we want `class BLAH {`

2023-11-07 00:40 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/CfgWeapons.hpp
> +        scope=1;
Missing spaces between all the equals and values

2023-11-07 00:40 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/CfgWeapons.hpp
> +        MRT_SwitchItemNextClass="QGVAR(CUP_LED_flashlight)";
Incorrect usage: `MRT_SwitchItemNextClass="QGVAR(CUP_LED_flashlight)";` -> `MRT_SwitchItemNextClass = QGVAR(CUP_LED_flashlight);` `QGVAR` adds the quotes

2023-11-07 00:40 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/script_component.hpp
> +#define COMPONENT strongerFlashLights
`strongerFlashLights` -> `strongerFlashlights` (this on me, sorry)

2023-11-07 01:32 UTC, TheCandianVendingMachine requested changes

2023-11-07 01:32 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +class CfgPatches
sorry chesh, one more file needs format fixes

2023-11-07 01:32 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +			"GVAR(Vanilla_HG_LED_flashlight_Flood)",
`"GVAR` -> `QGVAR

2023-11-07 01:34 UTC, AChesheireCat commented on addons/strongerFlashlights/config.cpp
> +class CfgPatches
no worries! updated :)

2023-11-07 01:45 UTC, TheCandianVendingMachine requested changes
`config.cpp` has inconsistent brace style, which were the aforementioned style issues 😅. New issues found as well :upside_down_face:

2023-11-07 01:45 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +	class ADDON
Braces inconsistent, need to be on same line

2023-11-07 01:45 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +			QGVAR(Vanilla_HG_LED_flashlight_Flood),
Tabs -> spaces

2023-11-07 01:45 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +		units[]=
`units[] = {};`

2023-11-07 01:45 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +		requiredVersion=0.1;
`requiredVersion=0.1` -> `requiredVersion = REQUIRED_VERSION` for consistency

2023-11-07 01:45 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +		requiredAddons[]={"cup_weapons_east_attachments", "cup_weapons_west_attachments", "ace_laserpointer"};
I think we want to add `skipWhenMissingDependencies = 1;`. See https://github.com/BourbonWarfare/POTATO/blob/master/addons/cswCompat/config.cpp#L8

2023-11-07 01:45 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +		author = "Carl, Chesheire";
`author = "Potato"`. Add `authors[] = {"Carl", "Cheshire"};`. See https://github.com/BourbonWarfare/POTATO/blob/master/addons/cswCompat/config.cpp#L10

2023-11-07 01:45 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +		authorUrl="";
`authorUrl = "https://github.com/BourbonWarfare/POTATO";` instead

2023-11-07 01:45 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +	};
Add `VERSION_CONFIG;`. See https://github.com/BourbonWarfare/POTATO/blob/master/addons/cswCompat/config.cpp#L12C9-L12C24

2023-11-07 01:47 UTC, TheCandianVendingMachine requested changes

2023-11-07 01:47 UTC, TheCandianVendingMachine commented on addons/strongerFlashlights/config.cpp
> +class CfgPatches
Need to include `#include "script_component.hpp"` at top of this file

2023-11-07 20:23 UTC, TheCandianVendingMachine approved these changes
lgtm, thanks for the style updates!

2023-11-23 07:33 UTC, merged